export const paths = {
  home: '/',
  teamPage: '/team',
  aboutPage: '/about',
  servicesPage: '/services',
  servicesPageId: '/services/:id',
  galleryPage: '/gallery',
  contactsPage: '/contacts',
  programPage: '/program',
  dailyDietPage: '/daily-diet',
  pricePage: '/price',
  reviewsPage: '/reviews',
  documentsPage: '/documents',
  scheduleGroupPage: '/schedule-group',
  dailyRoutinePage: '/daily-routine',
  teamId: '/team/:id',
};
